"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, PiggyBank } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/layout/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { formatCurrency } from "@/lib/utils/finance";

type BudgetData = { monthlyLimit: number; spent: number; remaining: number; categoryLimits: Record<string, number>; categories: { name: string; spent: number; color: string | null }[] };

export default function BudgetPage() {
  const [data, setData] = useState<BudgetData | null>(null); const [limit, setLimit] = useState(""); const [categoryLimits, setCategoryLimits] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false);
  function load() { return fetch("/api/budget").then((response) => response.json()).then((next) => { setData(next); setLimit(next.monthlyLimit ? String(next.monthlyLimit) : ""); setCategoryLimits(Object.fromEntries(Object.entries(next.categoryLimits || {}).map(([name, value]) => [name, String(value)]))); }); }
  useEffect(() => { load(); }, []);
  async function save() { setSaving(true); const response = await fetch("/api/budget", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ monthlyLimit: limit, categoryLimits }) }); setSaving(false); if (!response.ok) return toast.error("Could not save your budget"); toast.success("Budget updated"); load(); }
  const monthlyLimit = Number(limit) || 0; const spent = data?.spent || 0; const percentage = monthlyLimit ? Math.round(spent / monthlyLimit * 100) : 0; const overspending = monthlyLimit > 0 && spent > monthlyLimit;
  return <AppShell><div className="budget-page"><section className="budget-heading"><div><p className="eyebrow"><PiggyBank className="h-3.5 w-3.5" /> Monthly plan</p><h2>Stay ahead of overspending.</h2><p>Set a cash-out limit, then see exactly when spending needs attention.</p></div></section><section className={`budget-hero ${overspending ? "over" : ""}`}><div><p className="budget-label">{monthlyLimit ? (overspending ? "Over budget" : "Remaining this month") : "Set your monthly limit"}</p><strong>{monthlyLimit ? formatCurrency(Math.abs(monthlyLimit - spent)) : "₱0.00"}</strong><p>{monthlyLimit ? `${formatCurrency(spent)} spent of ${formatCurrency(monthlyLimit)}` : "Your cash-out target goes here."}</p></div><div className="budget-status">{overspending ? <AlertTriangle className="h-6 w-6" /> : <CheckCircle2 className="h-6 w-6" />}<span>{monthlyLimit ? (overspending ? "Time to slow down" : percentage >= 80 ? "Getting close" : "On track") : "No budget set"}</span></div><div className="budget-progress"><i style={{ width: `${Math.min(percentage, 100)}%` }} /></div></section><section className="budget-grid"><article className="panel budget-settings"><div className="panel-heading"><div><p className="section-kicker">YOUR LIMIT</p><h3>Monthly cash-out budget</h3></div></div><p>Choose the most you want to spend in a month. Cash In is never counted against it.</p><div className="budget-input"><span>₱</span><Input type="number" min="0" inputMode="decimal" value={limit} onChange={(event) => setLimit(event.target.value)} placeholder="0.00" /></div><Button onClick={save} disabled={saving}>{saving ? "Saving…" : "Save budget"}</Button></article><article className="panel category-budgets"><div className="panel-heading"><div><p className="section-kicker">BY SPENDING TYPE</p><h3>Category limits</h3></div></div><p className="panel-subtitle">Optional limits for categories you have used this month.</p>{data?.categories?.length ? <div className="budget-category-list">{data.categories.map((category) => { const categoryLimit = Number(categoryLimits[category.name]) || 0; const over = categoryLimit > 0 && category.spent > categoryLimit; return <div className="budget-category" key={category.name}><span style={{ backgroundColor: category.color || "#3ea96d" }} /><div><strong>{category.name}</strong><p className={over ? "over-text" : ""}>{formatCurrency(category.spent)} spent{categoryLimit ? ` of ${formatCurrency(categoryLimit)}` : ""}</p></div><Input type="number" min="0" inputMode="decimal" placeholder="Limit" value={categoryLimits[category.name] || ""} onChange={(event) => setCategoryLimits({ ...categoryLimits, [category.name]: event.target.value })} /></div>; })}<Button className="save-categories" onClick={save} disabled={saving}>Save category limits</Button></div> : <div className="empty-panel"><PiggyBank className="h-8 w-8" /><p>Your spending types will appear here once you record Cash Out.</p></div>}</article></section></div></AppShell>;
}
