"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Banknote, ChevronRight, CircleDollarSign, LayoutList, ReceiptText, Sparkles, WalletCards } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/layout/app-shell";
import { QuickRecordDialog } from "@/components/quick-record-dialog";
import { formatCurrency, formatDate } from "@/lib/utils/finance";
import type { Transaction } from "@/types/database";

type Spending = { name: string; amount: number; color: string | null };
type Point = { month: string; income: number; expense: number };
type CashData = { totalBalance: number; cashIn: number; cashOut: number; categorySpending: Spending[]; monthlySeries: Point[]; recentTransactions: Transaction[] };
const colors = ["#176f4b", "#3ea96d", "#7bc797", "#d4a55c"];
const chartTooltip = { background: "#fff", border: "1px solid #dceee3", borderRadius: "14px", color: "#173d2c", boxShadow: "0 14px 40px rgba(21,111,74,.12)", fontSize: 12 };

export default function DashboardPage() {
  const [data, setData] = useState<CashData | null>(null); const [loading, setLoading] = useState(true);
  function load() { setLoading(true); return fetch("/api/dashboard").then((response) => response.json()).then(setData).finally(() => setLoading(false)); }
  useEffect(() => { load(); }, []);
  const cashIn = data?.cashIn || 0; const cashOut = data?.cashOut || 0; const top = useMemo(() => (data?.categorySpending || []).slice(0, 4), [data?.categorySpending]); const hasChart = (data?.monthlySeries || []).some((point) => point.income || point.expense);
  if (loading) return <AppShell><div className="dashboard-loading"><div className="loading-orbit" /><p>Loading your cash book…</p></div></AppShell>;
  return <AppShell><div className="couples-dashboard cash-dashboard">
    <section className="dashboard-welcome"><div><div className="eyebrow"><Banknote className="h-3.5 w-3.5" /> Everyday cash book</div><h2>Know where your <span>cash goes.</span></h2><p>Record money in and money out in seconds. Nothing else gets in the way.</p></div><div className="dashboard-actions"><QuickRecordDialog type="expense" onSuccess={load} /><QuickRecordDialog type="income" onSuccess={load} /></div></section>
    <section className="balance-hero"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-main"><div className="hero-label"><WalletCards className="h-4 w-4" /> Cash on hand</div><p className="balance-value">{formatCurrency(data?.totalBalance || 0)}</p><div className="income-pill"><CircleDollarSign className="h-4 w-4" /> Updated with every cash record</div></div><div className="hero-aside"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-white/60">This month</p><p className="mt-1 text-sm font-medium">{formatCurrency(cashIn - cashOut)} net cash flow</p></div></div></section>
    <section className="quick-stats"><div className="stat-card"><span className="stat-icon green"><ArrowUpRight className="h-5 w-5" /></span><div><p>Cash in</p><strong>{formatCurrency(cashIn)}</strong><small>Received this month</small></div></div><div className="stat-card"><span className="stat-icon peach"><ArrowDownRight className="h-5 w-5" /></span><div><p>Cash out</p><strong>{formatCurrency(cashOut)}</strong><small>Spent this month</small></div></div><div className="stat-card"><span className="stat-icon mint"><CircleDollarSign className="h-5 w-5" /></span><div><p>Net cash flow</p><strong>{formatCurrency(cashIn - cashOut)}</strong><small>This month</small></div></div></section>
    <section className="dashboard-grid"><article className="panel flow-panel"><div className="panel-heading"><div><p className="section-kicker">CASH FLOW</p><h3>In and out over time</h3></div><span className="chart-note">Last 6 months</span></div>{hasChart ? <div className="chart-wrap"><ResponsiveContainer width="100%" height={230}><AreaChart data={data?.monthlySeries} margin={{ left: -20, right: 8, top: 8 }}><defs><linearGradient id="inGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2da66a" stopOpacity={.3} /><stop offset="100%" stopColor="#2da66a" stopOpacity={0} /></linearGradient><linearGradient id="outGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#ef9d80" stopOpacity={.2} /><stop offset="100%" stopColor="#ef9d80" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef5f0" strokeDasharray="3 3" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#7a9687", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#7a9687", fontSize: 10 }} tickFormatter={(value: number) => `₱${Math.round(value / 1000)}k`} /><Tooltip contentStyle={chartTooltip} formatter={(value: number) => formatCurrency(value)} /><Area type="monotone" dataKey="income" name="Cash in" stroke="#178b58" strokeWidth={2.5} fill="url(#inGradient)" /><Area type="monotone" dataKey="expense" name="Cash out" stroke="#e59075" strokeWidth={2.5} fill="url(#outGradient)" /></AreaChart></ResponsiveContainer></div> : <div className="empty-chart"><Sparkles className="h-7 w-7" />Your cash flow appears as soon as you add a record.</div>}</article>
    <article className="panel spending-panel"><div className="panel-heading"><div><p className="section-kicker">WHERE IT WENT</p><h3>Cash out overview</h3></div><Link href="/transactions" className="text-link">All records <ChevronRight className="h-4 w-4" /></Link></div>{top.length ? <div className="spending-list">{top.map((item, index) => { const percent = cashOut ? Math.round(item.amount / cashOut * 100) : 0; return <div className="spending-item" key={item.name}><span className="category-mark" style={{ backgroundColor: item.color || colors[index] }}>{item.name.slice(0, 1).toUpperCase()}</span><div className="spending-copy"><div><strong>{item.name}</strong><span>{percent}% of cash out</span></div><div className="spending-track"><i style={{ width: `${Math.max(percent, 5)}%`, backgroundColor: item.color || colors[index] }} /></div></div><strong className="spending-value">{formatCurrency(item.amount)}</strong></div>; })}</div> : <div className="empty-panel"><ReceiptText className="h-8 w-8" /><p>Cash-out records will build your spending overview.</p></div>}</article>
    <article className="panel activity-panel cash-activity"><div className="panel-heading"><div><p className="section-kicker">CASH BOOK</p><h3>Latest entries</h3></div><Link href="/transactions" className="text-link">Open cash book <ChevronRight className="h-4 w-4" /></Link></div>{data?.recentTransactions?.length ? <div className="activity-list">{data.recentTransactions.slice(0, 6).map((item) => { const out = item.type === "expense"; return <div className="activity-item" key={item.id}><span className={`transaction-icon ${out ? "expense" : "income"}`}>{out ? <ArrowDownRight className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}</span><div><strong>{item.description || (out ? "Cash out" : "Cash in")}</strong><p>{out ? "Cash out" : "Cash in"} · {formatDate(item.date)}</p></div><strong className={out ? "amount-expense" : "amount-income"}>{out ? "−" : "+"}{formatCurrency(item.amount)}</strong></div>; })}</div> : <div className="empty-panel compact"><LayoutList className="h-7 w-7" /><p>No entries yet. Start with the cash you received or spent today.</p></div>}</article></section>
  </div></AppShell>;
}
