"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Banknote, ChevronRight, CircleDollarSign, LayoutList, ReceiptText, Sparkles, WalletCards } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/layout/app-shell";
import { CashRecordActions } from "@/components/cash-record-actions";
import { CashWithdrawalDialog } from "@/components/cash-withdrawal-dialog";
import { formatCurrency, formatDate } from "@/lib/utils/finance";
import type { Account, Transaction } from "@/types/database";
import { CategoryIconBadge } from "@/components/category-icon";

type Spending = { name: string; amount: number; color: string | null };
type Period = "week" | "month";
type Point = { label: string; income: number; expense: number };
type CashData = { totalBalance: number; cashOnHand: number; cashAccounts: Pick<Account, "id" | "name" | "balance" | "color" | "type">[]; cashIn: number; cashOut: number; period: Period; periodLabel: string; categorySpending: Spending[]; cashSeries: Point[]; recentTransactions: Transaction[] };
const colors = ["#176f4b", "#3ea96d", "#7bc797", "#d4a55c"];
const chartTooltip = { background: "#fff", border: "1px solid #dceee3", borderRadius: "14px", color: "#173d2c", boxShadow: "0 14px 40px rgba(21,111,74,.12)", fontSize: 12 };

export default function DashboardPage() {
  const [data, setData] = useState<CashData | null>(null); const [loading, setLoading] = useState(true); const [period, setPeriod] = useState<Period>("month");
  const load = useCallback(() => { setLoading(true); return fetch(`/api/dashboard?period=${period}`).then((response) => response.json()).then(setData).finally(() => setLoading(false)); }, [period]);
  useEffect(() => { void load(); }, [load]);
  const cashIn = data?.cashIn || 0; const cashOut = data?.cashOut || 0; const cashOnHand = data?.cashOnHand || 0; const cashAccounts = data?.cashAccounts || []; const top = useMemo(() => (data?.categorySpending || []).slice(0, 4), [data?.categorySpending]); const hasChart = (data?.cashSeries || []).some((point) => point.income || point.expense); const periodLabel = data?.periodLabel || (period === "week" ? "This week" : "This month");
  if (loading) return <AppShell><div className="dashboard-loading"><div className="loading-orbit" /><p>Loading your cash book…</p></div></AppShell>;
  return <AppShell><div className="couples-dashboard cash-dashboard">
    <section className="dashboard-welcome"><div><div className="eyebrow"><Banknote className="h-3.5 w-3.5" /> Everyday cash book</div><h2>Know where your <span>cash goes.</span></h2><p>Record money in and money out in seconds. Nothing else gets in the way.</p></div><div className="dashboard-actions"><div className="dashboard-period-filter" role="group" aria-label="Cash activity period"><button type="button" className={period === "week" ? "active" : ""} onClick={() => setPeriod("week")}>Week</button><button type="button" className={period === "month" ? "active" : ""} onClick={() => setPeriod("month")}>Month</button></div><CashWithdrawalDialog onSuccess={load} /><CashRecordActions onSuccess={load} /></div></section>
    <section className="balance-hero"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-main"><div className="hero-label"><WalletCards className="h-4 w-4" /> Total available cash</div><p className="balance-value">{formatCurrency(data?.totalBalance || 0)}</p><div className="income-pill"><CircleDollarSign className="h-4 w-4" /> Cash and cash equivalents</div>{cashAccounts.length ? <div className="cash-account-tiles">{cashAccounts.slice(0, 4).map((account) => <Link className="cash-account-tile" href="/accounts" key={account.id}><span className="cash-account-dot" style={{ backgroundColor: account.color }} /><span>{account.name}</span><strong>{formatCurrency(Number(account.balance))}</strong></Link>)}</div> : <Link className="cash-account-empty" href="/accounts">Add a cash account to see its balance here <ChevronRight className="h-4 w-4" /></Link>}</div><div className="hero-aside"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-white/60">{periodLabel}</p><p className="mt-1 text-sm font-medium">{formatCurrency(cashIn - cashOut)} net cash flow</p></div></div></section>
    <section className="quick-stats"><div className="stat-card"><span className="stat-icon mint"><WalletCards className="h-5 w-5" /></span><div><p>Cash on hand</p><strong>{formatCurrency(cashOnHand)}</strong><small>Cash wallet</small></div></div><div className="stat-card"><span className="stat-icon green"><ArrowUpRight className="h-5 w-5" /></span><div><p>Total deposits</p><strong>{formatCurrency(cashIn)}</strong><small>Received {period === "week" ? "this week" : "this month"}</small></div></div><div className="stat-card"><span className="stat-icon peach"><ArrowDownRight className="h-5 w-5" /></span><div><p>Expenses</p><strong>{formatCurrency(cashOut)}</strong><small>Spent {period === "week" ? "this week" : "this month"}</small></div></div></section>
    <section className="dashboard-grid"><article className="panel flow-panel"><div className="panel-heading"><div><p className="section-kicker">CASH FLOW</p><h3>In and out over time</h3></div><span className="chart-note">{periodLabel}</span></div>{hasChart ? <div className="chart-wrap"><ResponsiveContainer width="100%" height={230}><AreaChart data={data?.cashSeries} margin={{ left: -20, right: 8, top: 8 }}><defs><linearGradient id="inGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2da66a" stopOpacity={.3} /><stop offset="100%" stopColor="#2da66a" stopOpacity={0} /></linearGradient><linearGradient id="outGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#ef9d80" stopOpacity={.2} /><stop offset="100%" stopColor="#ef9d80" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef5f0" strokeDasharray="3 3" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "#7a9687", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#7a9687", fontSize: 10 }} tickFormatter={(value: number) => `₱${Math.round(value / 1000)}k`} /><Tooltip contentStyle={chartTooltip} formatter={(value: number) => formatCurrency(value)} /><Area type="monotone" dataKey="income" name="Cash in" stroke="#178b58" strokeWidth={2.5} fill="url(#inGradient)" /><Area type="monotone" dataKey="expense" name="Cash out" stroke="#e59075" strokeWidth={2.5} fill="url(#outGradient)" /></AreaChart></ResponsiveContainer></div> : <div className="empty-chart"><Sparkles className="h-7 w-7" />Your cash flow appears as soon as you add a record.</div>}</article>
    <article className="panel spending-panel"><div className="panel-heading"><div><p className="section-kicker">WHERE IT WENT</p><h3>Cash out overview</h3></div><Link href="/transactions" className="text-link">All records <ChevronRight className="h-4 w-4" /></Link></div>{top.length ? <div className="spending-list">{top.map((item, index) => { const percent = cashOut ? Math.round(item.amount / cashOut * 100) : 0; return <div className="spending-item" key={item.name}><CategoryIconBadge category={item.name} className="category-mark" /><div className="spending-copy"><div><strong>{item.name}</strong><span>{percent}% of cash out</span></div><div className="spending-track"><i style={{ width: `${Math.max(percent, 5)}%`, backgroundColor: item.color || colors[index] }} /></div></div><strong className="spending-value">{formatCurrency(item.amount)}</strong></div>; })}</div> : <div className="empty-panel"><ReceiptText className="h-8 w-8" /><p>Cash-out records will build your spending overview.</p></div>}</article>
    <article className="panel activity-panel cash-activity"><div className="panel-heading"><div><p className="section-kicker">CASH BOOK</p><h3>Latest entries</h3></div><Link href="/transactions" className="text-link">Open cash book <ChevronRight className="h-4 w-4" /></Link></div>{data?.recentTransactions?.length ? <div className="activity-list">{data.recentTransactions.slice(0, 6).map((item) => { const out = item.type === "expense"; return <div className="activity-item" key={item.id}><span className={`transaction-icon ${out ? "expense" : "income"}`}>{out ? <ArrowDownRight className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}</span><div><strong>{item.description || (out ? "Cash out" : "Cash in")}</strong><p>{out ? "Cash out" : "Cash in"} · {formatDate(item.date)}</p></div><strong className={out ? "amount-expense" : "amount-income"}>{out ? "−" : "+"}{formatCurrency(item.amount)}</strong></div>; })}</div> : <div className="empty-panel compact"><LayoutList className="h-7 w-7" /><p>No entries yet. Start with the cash you received or spent today.</p></div>}</article></section>
  </div></AppShell>;
}
