"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, ChevronRight, CircleDollarSign, LayoutList, ReceiptText, Sparkles, UsersRound, WalletCards } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/layout/app-shell";
import { QuickRecordDialog } from "@/components/quick-record-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formatCurrency, formatDate } from "@/lib/utils/finance";
import type { Account, ScheduledTransaction, Transaction } from "@/types/database";

type CategorySpending = { name: string; amount: number; color: string | null };
type MemberContribution = { name: string; income: number; expense: number };
type MonthlyPoint = { month: string; income: number; expense: number };
type DashboardData = { needsHousehold?: boolean; totalBalance?: number; monthlyIncome?: number; monthlyExpenses?: number; categorySpending?: CategorySpending[]; contributionBreakdown?: MemberContribution[]; monthlySeries?: MonthlyPoint[]; recentTransactions?: Transaction[]; upcomingPayments?: ScheduledTransaction[]; accounts?: Account[] };
type Household = { id: string; name: string; currency: string; invite_code: string };

const spendingColors = ["#176f4b", "#3ea96d", "#7bc797", "#d4a55c"];
const chartTooltip = { background: "#fff", border: "1px solid #dceee3", borderRadius: "14px", color: "#173d2c", boxShadow: "0 14px 40px rgba(21,111,74,.12)", fontSize: 12 };
const initials = (name: string) => name.split(" ").filter(Boolean).slice(0, 2).map((word) => word[0]).join("").toUpperCase();

function HouseholdSetup({ onComplete }: { onComplete: () => void }) {
  const [mode, setMode] = useState<"create" | "join">("create");
  const [name, setName] = useState("");
  const [householdName, setHouseholdName] = useState("");
  const [code, setCode] = useState("");
  const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); const endpoint = mode === "create" ? "/api/household" : "/api/household/join"; const body = mode === "create" ? { displayName: name, householdName } : { displayName: name, inviteCode: code }; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setSaving(false); if (response.ok) onComplete(); }
  return <div className="setup-screen"><div className="setup-card"><div className="setup-symbol"><UsersRound className="h-7 w-7" /></div><p className="section-kicker">A SHARED START</p><h2>Set up your money space</h2><p>Use your own sign-ins, record your own contributions, and see one shared picture.</p><div className="setup-switch"><button className={mode === "create" ? "active" : ""} onClick={() => setMode("create")}>Create a household</button><button className={mode === "join" ? "active" : ""} onClick={() => setMode("join")}>Join your partner</button></div><form onSubmit={submit}><Label>Your name</Label><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="How should your partner see you?" required />{mode === "create" ? <><Label>Household name</Label><Input value={householdName} onChange={(event) => setHouseholdName(event.target.value)} placeholder="e.g. The Santos home" required /></> : <><Label>Household code</Label><Input value={code} onChange={(event) => setCode(event.target.value)} placeholder="Ask your partner for their code" required /></>}<Button type="submit" className="w-full" disabled={saving}>{saving ? "Saving…" : mode === "create" ? "Create shared space" : "Join household"}</Button></form></div></div>;
}

export default function DashboardPage() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [household, setHousehold] = useState<Household | null>(null);
  const [loading, setLoading] = useState(true);
  function load() { setLoading(true); return Promise.all([fetch("/api/dashboard").then((response) => response.json()), fetch("/api/household").then((response) => response.json())]).then(([dashboard, householdData]) => { setData(dashboard); setHousehold(householdData.household); }).finally(() => setLoading(false)); }
  useEffect(() => { load(); }, []);
  const expenses = data?.monthlyExpenses || 0;
  const income = data?.monthlyIncome || 0;
  const topSpending = useMemo(() => (data?.categorySpending || []).slice(0, 4), [data?.categorySpending]);
  const contributors = data?.contributionBreakdown || [];
  const hasChart = (data?.monthlySeries || []).some((month) => month.income || month.expense);
  if (loading) return <AppShell><div className="dashboard-loading"><div className="loading-orbit" /><p>Preparing your shared money view…</p></div></AppShell>;
  if (data?.needsHousehold) return <AppShell><HouseholdSetup onComplete={load} /></AppShell>;
  return <AppShell><div className="couples-dashboard overhaul-dashboard">
    <section className="dashboard-welcome"><div><div className="eyebrow"><UsersRound className="h-3.5 w-3.5" /> Shared household</div><h2>{household?.name || "Your money space"}</h2><p>Every record is attributed to the person who added it—no forced splits.</p></div><div className="dashboard-actions"><QuickRecordDialog type="expense" onSuccess={load} /><QuickRecordDialog type="income" onSuccess={load} /></div></section>
    <section className="balance-hero"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-main"><div className="hero-label"><WalletCards className="h-4 w-4" /> Shared cash available</div><p className="balance-value">{formatCurrency(data?.totalBalance || 0)}</p><div className="income-pill"><CircleDollarSign className="h-4 w-4" /> Real-time household balance</div></div><div className="hero-aside"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-white/60">Invite your partner</p><p className="mt-1 text-sm font-medium">Code: <span className="tracking-[.18em]">{household?.invite_code || "—"}</span></p></div></div></section>
    <section className="quick-stats"><div className="stat-card"><span className="stat-icon green"><ArrowUpRight className="h-5 w-5" /></span><div><p>Total contributed</p><strong>{formatCurrency(income)}</strong><small>Money in this month</small></div></div><div className="stat-card"><span className="stat-icon peach"><ArrowDownRight className="h-5 w-5" /></span><div><p>Household spending</p><strong>{formatCurrency(expenses)}</strong><small>Money out this month</small></div></div><div className="stat-card"><span className="stat-icon mint"><CircleDollarSign className="h-5 w-5" /></span><div><p>Monthly breathing room</p><strong>{formatCurrency(income - expenses)}</strong><small>Contribution minus spend</small></div></div></section>
    <section className="dashboard-grid"><article className="panel contribution-panel"><div className="panel-heading"><div><p className="section-kicker">CONTRIBUTIONS</p><h3>Who put in what</h3></div><span className="equal-split"><UsersRound className="h-4 w-4" /> Actual records</span></div><p className="panel-subtitle">Income and spending are assigned automatically to the person who records them.</p>{contributors.length ? <div className="contribution-list">{contributors.map((person, index) => <div className="contributor" key={person.name}><span className="contributor-avatar" style={{ background: spendingColors[index % spendingColors.length] }}>{initials(person.name)}</span><div><strong>{person.name}</strong><p><span>Contributed {formatCurrency(person.income)}</span><span>Spent {formatCurrency(person.expense)}</span></p></div><strong className="contributor-net">{formatCurrency(person.income - person.expense)}</strong></div>)}</div> : <div className="empty-panel"><UsersRound className="h-8 w-8" /><p>As each person records money in or out, their real contribution appears here.</p></div>}</article>
    <article className="panel spending-panel"><div className="panel-heading"><div><p className="section-kicker">SPENDING MAP</p><h3>Top expenses</h3></div><Link href="/categories" className="text-link">Categories <ChevronRight className="h-4 w-4" /></Link></div>{topSpending.length ? <div className="spending-list">{topSpending.map((category, index) => { const percent = expenses ? Math.round(category.amount / expenses * 100) : 0; return <div className="spending-item" key={category.name}><span className="category-mark" style={{ backgroundColor: category.color || spendingColors[index] }}>{initials(category.name)}</span><div className="spending-copy"><div><strong>{category.name}</strong><span>{percent}% of all expenses</span></div><div className="spending-track"><i style={{ width: `${Math.max(percent, 5)}%`, backgroundColor: category.color || spendingColors[index] }} /></div></div><strong className="spending-value">{formatCurrency(category.amount)}</strong></div>; })}</div> : <div className="empty-panel"><ReceiptText className="h-8 w-8" /><p>Record money out to see where your household is spending.</p></div>}</article>
    <article className="panel flow-panel"><div className="panel-heading"><div><p className="section-kicker">MONEY RHYTHM</p><h3>In &amp; out over time</h3></div><span className="chart-note">Last 6 months</span></div>{hasChart ? <div className="chart-wrap"><ResponsiveContainer width="100%" height={230}><AreaChart data={data?.monthlySeries} margin={{ left: -20, right: 8, top: 8 }}><defs><linearGradient id="incomeGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2da66a" stopOpacity={.3} /><stop offset="100%" stopColor="#2da66a" stopOpacity={0} /></linearGradient><linearGradient id="expenseGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#ef9d80" stopOpacity={.2} /><stop offset="100%" stopColor="#ef9d80" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef5f0" strokeDasharray="3 3" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#7a9687", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#7a9687", fontSize: 10 }} tickFormatter={(value: number) => `₱${Math.round(value / 1000)}k`} /><Tooltip contentStyle={chartTooltip} formatter={(value: number) => formatCurrency(value)} /><Area type="monotone" dataKey="income" name="Money in" stroke="#178b58" strokeWidth={2.5} fill="url(#incomeGradient)" /><Area type="monotone" dataKey="expense" name="Money out" stroke="#e59075" strokeWidth={2.5} fill="url(#expenseGradient)" /></AreaChart></ResponsiveContainer></div> : <div className="empty-chart"><Sparkles className="h-7 w-7" />Your money rhythm will appear as you record it.</div>}</article>
    <article className="panel activity-panel"><div className="panel-heading"><div><p className="section-kicker">LATEST RECORDS</p><h3>Household activity</h3></div><Link href="/transactions" className="text-link">View all <ChevronRight className="h-4 w-4" /></Link></div>{data?.recentTransactions?.length ? <div className="activity-list">{data.recentTransactions.slice(0, 4).map((transaction) => { const expense = transaction.type === "expense"; return <div className="activity-item" key={transaction.id}><span className={`transaction-icon ${expense ? "expense" : "income"}`}>{expense ? <ArrowDownRight className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}</span><div><strong>{transaction.description || (expense ? "Money out" : "Money in")}</strong><p>{transaction.contributor_name} · {formatDate(transaction.date)}</p></div><strong className={expense ? "amount-expense" : "amount-income"}>{expense ? "−" : "+"}{formatCurrency(transaction.amount)}</strong></div>; })}</div> : <div className="empty-panel compact"><LayoutList className="h-7 w-7" /><p>Your shared records will appear here.</p></div>}</article></section>
  </div></AppShell>;
}
